// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEFF9_LrrqwnV0Bj5nxgdqUhMmc2zCg8',
    appId: '1:165784649696:web:67f0847e21e58b37017585',
    messagingSenderId: '165784649696',
    projectId: 'flutter-insta-clone-5c983',
    authDomain: 'flutter-insta-clone-5c983.firebaseapp.com',
    storageBucket: 'flutter-insta-clone-5c983.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACGOXTPW-7RT23iEG-wbNvCa1-p_D9flU',
    appId: '1:165784649696:android:eba32a8f69dc5c2c017585',
    messagingSenderId: '165784649696',
    projectId: 'flutter-insta-clone-5c983',
    storageBucket: 'flutter-insta-clone-5c983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIJef5r5PFCoMqoLfPqtSRovPxrMThv3s',
    appId: '1:165784649696:ios:1c477a66cfd5b133017585',
    messagingSenderId: '165784649696',
    projectId: 'flutter-insta-clone-5c983',
    storageBucket: 'flutter-insta-clone-5c983.appspot.com',
    androidClientId: '165784649696-bfhht3gi7famr0rd5q776qfa19nmbik3.apps.googleusercontent.com',
    iosClientId: '165784649696-p8ucgim09v81ln4dis0bca1a2adfb264.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIJef5r5PFCoMqoLfPqtSRovPxrMThv3s',
    appId: '1:165784649696:ios:1c477a66cfd5b133017585',
    messagingSenderId: '165784649696',
    projectId: 'flutter-insta-clone-5c983',
    storageBucket: 'flutter-insta-clone-5c983.appspot.com',
    androidClientId: '165784649696-bfhht3gi7famr0rd5q776qfa19nmbik3.apps.googleusercontent.com',
    iosClientId: '165784649696-p8ucgim09v81ln4dis0bca1a2adfb264.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstaClone',
  );
}
